### ISSUE TITLE
Update to current conversion standards

### ISSUE THREAD

**Issue by robchandhok** [ha-warmup/hacs-warmup#5]
As of 2023.3, getting these messages in the log:

```
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for warmup using this method at custom_components/warmup/climate.py, line 315: return convert_temperature(
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for warmup using this method at custom_components/warmup/climate.py, line 322: return convert_temperature(
```

Need to cleanup

**Comment by artmg** [comment]
Hi @robchandhok the temperature utility should already have been removed from the newly restructured repo that replaces this one as the warmup integration for HACS: https://github.com/ha-warmup/warmup - for any issues outstanding, please raise them in https://github.com/ha-warmup/warmup/issues 

If you want to assign yourself any issues to kindly offer your time to work on in the other project, especially regarding temperature, please do have a look at the thread in [Rationalise temperature localisation #48](https://github.com/ha-warmup/warmup/issues/48)

Thanks
