### ISSUE TITLE
How to keep in sync with main ha-warmup project?

### ISSUE THREAD

**Issue by artmg** [ha-warmup/hacs-warmup#7]
Identify possible ways to make it easier to also bring changes into this project when they are made in the main [ha-warmup/warmup](https://github.com/ha-warmup/warmup) project.

1.  Start by clarifying exactly what is different from and which sections should be identical to the main project.
2. Consider what might be the repercussions of adding those differences permanently into the main project, as far as code, documentation, installation, testing etc goes.
3. work out what other options there might be

**Comment by artmg** [comment]
Some of the differences are indicated from when @robchandhok created his fork, and referenced in [these comments on main warmup project issue #30](https://github.com/ha-warmup/warmup/issues/30#issuecomment-895552689)

**Comment by artmg** [comment]
Perhaps a better place to discuss any options might be in the [proposal to restructure the main project in issue #50](https://github.com/ha-warmup/warmup/issues/50)

**Comment by rct** [comment]
Why is this a different repo instead of a branch on the original repo?

- https://github.com/ha-warmup/warmup/issues/50#issuecomment-1460751770)

Let's not spend what little resources there are willing to work on this trying to keep multiple repos in sync and having to communicate which repo to look at for updates, etc.

**Comment by robchandhok** [comment]
That’s the point. It shouldn’t be a different repo or branch. It should be structured for HACS which is a fine structure for a manual installation.

**Comment by artmg** [comment]
The newly restructured repo that replaces this one as the warmup integration for HACS: https://github.com/ha-warmup/warmup
